### ISSUE TITLE
BO001 - No hay tutorial

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#1]
Al iniciar una partida no hay instrucciones de juego

Reproduction rate: 100%

_Pasos de reproducción:_
Iniciar el juego.
Tap sobre el botón de Play
Elegir el primer nivel

_Resultado esperado:_
Tutorial con reglas básicas del juego.

_Resultado obtenido:_
El juego comienza sin instrucciones.

**Comment by Lisandrog210** [comment]
Se considera tutorial a los primeros niveles, porque hay un panel en el primero que te dice los controles, lo que paso es que estaba desactivado por error cuando lo probaste.
