### ISSUE TITLE
BO010 - No hay respawn de plataformas luego de tocarlas

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#10]
En el nivel dos del Jungle World, luego de pasar el segundo checkpoint se debe subir a una plataforma que sube y baja. De ahí se salta a otra con las mismas características y que nos obliga a saltar a otras que desaparecen luego de tocarlas. De desaparecer las plataformas y no sobrevivir a la caída, no hay respawn de esas plataformas por lo que no es posible continuar el nivel.

Reproduction rate: 100%.

_Pasos de reproducción:_
Iniciar el juego.
Tap en el botón Play.
Jugar el nivel 1 y ganarlo.
Elegir el nivel 2.
Llegar hasta el 2do checkpoint.
Subir a la primer plataforma móvil.
Subir a la segunda plataforma móvil.
Saltar a las plataformas que desaparecen.
Sobrevivir la caída.
Volver a la altura de las plataformas que desaparecen.

_Resultado esperado:_
Que reaparezcan las plataformas para continuar el nivel.

_Resultado obtenido:_
No se puede continuar el juego.

**Comment by Lisandrog210** [comment]
Solucionado.
