### ISSUE TITLE
BO013 - Score erróneo

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#13]
En el nivel 1 de Jungle World cuando se obtiene una estrella y se vuelve al menú de selección de niveles figura como que se obtuvieron 2. Si se obtuvieron 2 figura que se obtuvieron obtienen 3.

Reproduction rate: No se pudo reproducir.

Pasos de reproducción:
Iniciar el juego.
Tap en botón Play.
Elegir nivel 1 de Jungle World.
Obtener por lo menos una estrella.

Resultado esperado:
_En el level select ver la cantidad de estrellas obtenidas en el nivel._

Resultado obtenido:
_Hay más estrellas de las que se acumularon._

**Comment by rodrigoperalta** [comment]
Esto es lo que te habiamos mencionado que no habiamos podido reproducir pero que al mismo tiempo encontramos otro bug (que lo ocasionaba algo que hicimos para testear) y lo solucionamos. Se da por solucionado?

**Comment by ElFantasma667** [comment]
Si no se puede reproducir lo pueden pasar a wont fix o cerrarlo. El bug que encontraron ustedes yo no lo registré así que queda para ustedes, o si quieren lo pueden subir y pasarlo a closed.
