### ISSUE TITLE
BO017 - Backwards de menú pausa entra en conflicto con el tap

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#17]
Al hacer tap en el botón backwards para volver al juego del menú de pausa acciona la función de salto de la bola.

Reproduction rate: 100%.

_Pasos de reproducción:_
Iniciar el juego.
Tap en el botón Play
Elegir un nivel
Poner pausa
Tocar el botón backwards para volver al juego

_Resultado esperado:_
Bola en la posición previa a la pausa.

_Resultado obtenido:_
Salto de bola.

https://drive.google.com/open?id=1-Gb8GHyVfW08z2zR8ptrNM_booHzLvxr

**Comment by Lisandrog210** [comment]
Solucionado.

**Comment by Lisandrog210** [comment]
Solucionado.
