### ISSUE TITLE
BO019 - Elemento de fondo queda en primer plano

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#19]
En el nivel 2 de Jungle World la antorcha del segundo checkpoint queda en primer plano cuando la plataforma pasa por el objeto.

Reproduction rate: 100%.

_Pasos de reproducción:_
Iniciar el juego
Tap al botón Play
Elegir el nivel 2 de Jungle World
Llegar al segundo checkpoint.

_Resultado esperado:_
Antorcha en segundo plano.

_Resultado obtenido:_
Antorcha en primer plano

![screenshot_20181109-203739](https://user-images.githubusercontent.com/44785585/48369402-2fb97900-e695-11e8-91f3-d71d14926994.png)

**Comment by Lisandrog210** [comment]
Solucionado.

**Comment by ElFantasma667** [comment]
Vuelve a suceder en versión 0.11

**Comment by Lisandrog210** [comment]
No lo pude recrear, quizas tocando las capas se soluciono. Mas que nada me refiero a los prefabs.
