### ISSUE TITLE
BO020 - N1 Jungle World no funciona el botón de pausa

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#20]
En el nivel 1 del Jungle World al tocar el botón de pausa no funciona y hace el tap de salto.

Reproduction rate: 100%.

_Pasos de Reproducción:_
Iniciar el juego.
Tap en botón Play.
Elegir nivel 1 de Jungle World.
Tap al botón Pausa.

_Resultado esperado:_
Menú de pausa y juego pausado.

_Resultado obtenido:_
Salto de la bola.

https://drive.google.com/open?id=1OgMGpbAly_StVkey-QQarYHRk_-moGhh

**Comment by Lisandrog210** [comment]
Solucionado.
