### ISSUE TITLE
BO024 - N1 Ice World no hay respawn de miniplataformas

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#24]
Al comienzo del nivel 1 de Ice World se deben atravesar una miniplataformas que desaparecen luego de tocarlas. Si por algún motivo no las podemos atravesar no respawnean y no se puede continuar el nivel.

Reproduction rate: 100%.

_Pasos de reproducción:_
Iniciar el juego.
Tap en botón Play.
Ganar los niveles de Jungle World y Fire World.
Iniciar el nivel 1 de Ice World.

_Resultado esperado:_
Respawn de las miniplataformas para poder atravesar el obstáculo.

_Resultado obtenido:_
No hay respawn.

https://drive.google.com/open?id=1qOG1l-ToeG6522bvExpFuMLsc1wQnqe7

**Comment by Lisandrog210** [comment]
Esta duplicado este bug. El original ya está cerrado.
