### ISSUE TITLE
BO003 - No hay botón de exit

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#3]
No se puede salir del juego ya que no hay botón de exit.

Reproduction rate: 100%

_Pasos de reproducción:_
Iniciar el juego
Tap sobre el botón Play / Ver pantalla de selección de nivel

_Resultado esperado:_
Botón para salir del juego

_Resultado obtenido:_
No se puede salir del juego.

**Comment by Lisandrog210** [comment]
Es intencional.
