### ISSUE TITLE
BO005 - Botón de backwards no funciona

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#5]
Al apretar el botón backwards del display inferior de Android no vuelve a la pantalla principal ni al menú principal del juego.

Reproduction rate: 100%

_Pasos de reproducción:_
Iniciar el juego.
Tap en botón Play
Elegir un nivel.
Slide con el dedo al display inferior de Android.
Tap al botón backwards.

_Resultado esperado:_
Vuelta al menú de selección de nivel / vuelta la pantalla principal del SO.

_Resultado obtenido:_
Null.

https://drive.google.com/open?id=1Mq0SadBVP3is8FuZpOCpPAfm6K8ac4ve

**Comment by Lisandrog210** [comment]
Te referis al boton DE android? Agregamos boton de backwards INGAME para que haya que usar ese tipo de botones ya que hay celulares que no lo tienen.

**Comment by ElFantasma667** [comment]
El botón al que me refiero es el Back. En casi todas las versiones de Android está a la izquierda de home en la barra inferior ya sea física o virtual. Si bien algunos lo tienen en forma física, entiendo que debería haber alguna solución para los que tenemos la barra virtual.
