### ISSUE TITLE
BO007 - Mini plataformas desaparecen luego de tocarlas

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#7]
En el nivel 1 del Jungle World, las plataformas pequeñas (triángulo invertido) desaparecen luego de tocarlas.

_Reproduction rate: 100%_
Pasos de reproducción:
Iniciar el juego
Tap en botón Play
Elegir el nivel 1 del Jungle World
Tocar las plataformas pequeñas y saltar a otra plataforma.

_Resultado esperado:_
Plataformas en pantalla.

_Resultado obtenido:_
Desaparecen las plataformas.

https://drive.google.com/open?id=1457E1ycDt3m03Ws5sqjk6fSDZgWkkpoc

**Comment by Lisandrog210** [comment]
Las plataformas que desaparecen lo hacen intencionalmente. Les falta una animación.

**Comment by Lisandrog210** [comment]
Es intencional.
