### ISSUE TITLE
BO009 - No hay botón de pausa

### ISSUE THREAD

**Issue by ElFantasma667** [Lisandrog210/BallOdyssey#9]
No hay forma de pausar las partidas.

Reproduction rate: 100%

_Pasos de reproducción:_
Iniciar el juego.
Tap al botón Play.
Elegir un nivel.

_Resultado esperado:_
Botón / opción de pausa.

_Resultado obtenido:_
No se puede pausar el juego.

**Comment by Lisandrog210** [comment]
Agregado.
